/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_soeholm_android_fibonacciproject_fibonacciservice_Fibonacci */

#ifndef _Included_me_soeholm_android_fibonacciproject_fibonacciservice_Fibonacci
#define _Included_me_soeholm_android_fibonacciproject_fibonacciservice_Fibonacci
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_soeholm_android_fibonacciproject_fibonacciservice_Fibonacci
 * Method:    fibNR
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_me_soeholm_android_fibonacciproject_fibonacciservice_Fibonacci_fibNR
  (JNIEnv *, jclass, jlong);

/*
 * Class:     me_soeholm_android_fibonacciproject_fibonacciservice_Fibonacci
 * Method:    fibNI
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_me_soeholm_android_fibonacciproject_fibonacciservice_Fibonacci_fibNI
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
